name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
            cd application
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
    
      - name: Deploy Application
        run: |
          cd application
          aws eks update-kubeconfig --name my-eks-cluster --region us-west-2
          kubectl apply -f deployment.yaml
