name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v2.6.0/trivy_2.6.0_Linux-64bit.tar.gz
          tar zxvf trivy_2.6.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Build and push image
        run: |
          cd application
          echo ${{ env.DOCKER_TOKEN }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ env.DOCKER_USERNAME }}/MaxApp:latest -f Dockerfile .
          trivy image --exit-code 1 --no-progress --format json ${{ env.DOCKER_USERNAME }}/MaxApp:latest
          docker push ${{ env.DOCKER_USERNAME }}/MaxApp:latest
