name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
          cd application
          docker build -t dolapofashina/my-python-app:latest .
          docker tag my-python-app ${{ secrets.DOCKER_USERNAME }}/my-python-app
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app

      - name: Deploy Application
        run: |
          cd application
          aws eks update-kubeconfig --name my-eks-cluster --region us-west-2
          kubectl apply -f deployment.yaml
