name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Build and Push Docker Image
        run: |
          cd application
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/MaxApp:latest .
          trivy image --exit-code 1 --no-progress --format json ${{ secrets.DOCKER_USERNAME }}/MaxApp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    
      - name: Deploy Application
        run: |
          cd application
          aws eks update-kubeconfig --name my-eks-cluster --region us-west-2
          kubectl apply -f deployment.yaml
